"use client";
import Link from "next/link";
import { use, useEffect, useState } from "react";
import { CandidateForm } from "@/components/CandidateForm";
import { StatusBadge } from "@/components/StatusBadge";
import { api } from "@/lib/api";
import { candidateName, candidatePosition, stages, stageLabels, statuses, statusLabels, type Candidate, type Note, type Stage, type Status } from "@/types";

export default function CandidateDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [candidate, setCandidate] = useState<Candidate | null>(null); const [notes, setNotes] = useState<Note[]>([]); const [loading, setLoading] = useState(true); const [notesLoading, setNotesLoading] = useState(true); const [error, setError] = useState(""); const [note, setNote] = useState(""); const [feedback, setFeedback] = useState(""); const [editing, setEditing] = useState(false);
  useEffect(() => { let active = true; api.getCandidate(id).then((data) => { if (active) setCandidate(data); }).catch((err) => { if (active) setError(err instanceof Error ? err.message : "No se pudo cargar la candidatura."); }).finally(() => { if (active) setLoading(false); }); api.getNotes(id).then((data) => { if (active) setNotes(data); }).catch((err) => { if (active) setFeedback(err instanceof Error ? err.message : "No se pudieron cargar las notas."); }).finally(() => { if (active) setNotesLoading(false); }); return () => { active = false; }; }, [id]);
  const update = async (field: "status" | "stage", value: Status | Stage) => { if (!candidate) return; try { const updated = await api.updateCandidate(candidate.id, { [field]: value }); setCandidate(updated); setFeedback("Cambio guardado correctamente."); } catch (err) { setFeedback(err instanceof Error ? err.message : "No se pudo actualizar."); } };
  const addNote = async (event: React.FormEvent) => { event.preventDefault(); if (!note.trim()) return; try { const created = await api.addNote(id, note.trim()); setNotes((current) => [created, ...current]); setNote(""); setFeedback("Nota añadida."); } catch (err) { setFeedback(err instanceof Error ? err.message : "No se pudo añadir la nota."); } };
  const removeNote = async (noteId: number) => { try { await api.removeNote(id, noteId); setNotes((current) => current.filter((item) => item.id !== noteId)); setFeedback("Nota eliminada."); } catch (err) { setFeedback(err instanceof Error ? err.message : "No se pudo eliminar la nota."); } };
  if (loading) return <main className="shell"><div className="state">Cargando candidatura...</div></main>;
  if (error || !candidate) return <main className="shell"><Link className="back-link" href="/">← Volver al listado</Link><div className="state state-error" role="alert">{error || "Candidatura no encontrada."}</div></main>;
  return <main className="shell"><Link className="back-link" href="/">← Volver al listado</Link><header className="detail-header"><div><p className="eyebrow">CANDIDATURA #{candidate.id}</p><h1>{candidateName(candidate)}</h1><p className="detail-subtitle">{candidatePosition(candidate)} · {candidate.email}</p></div><div className="detail-badges"><StatusBadge value={candidate.status} /><StatusBadge value={candidate.stage} kind="stage" /></div></header>
    {feedback && <p className="feedback" role="status">{feedback}</p>}
    <div className="detail-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">DATOS DEL PERFIL</p><h2>Información completa</h2></div><button className="button button-quiet" onClick={() => setEditing((value) => !value)}>{editing ? "Cerrar edición" : "Editar datos"}</button></div>{editing ? <CandidateForm candidate={candidate} onDone={(updated) => { setCandidate(updated); setEditing(false); setFeedback("Candidatura actualizada correctamente."); }} onCancel={() => setEditing(false)} /> : <dl className="profile-grid"><div><dt>Nombre</dt><dd>{candidateName(candidate)}</dd></div><div><dt>Email</dt><dd><a href={`mailto:${candidate.email}`}>{candidate.email}</a></dd></div><div><dt>Teléfono</dt><dd>{candidate.phone || "No indicado"}</dd></div><div><dt>Puesto</dt><dd>{candidatePosition(candidate)}</dd></div><div><dt>LinkedIn</dt><dd>{(candidate.linkedin || candidate.linkedin_url) ? <a href={candidate.linkedin || candidate.linkedin_url} target="_blank" rel="noreferrer">Abrir perfil</a> : "No indicado"}</dd></div><div><dt>CV</dt><dd>{(candidate.resume_url || candidate.cv_url) ? <a href={candidate.resume_url || candidate.cv_url} target="_blank" rel="noreferrer">Abrir CV</a> : "No indicado"}</dd></div><div><dt>Experiencia</dt><dd>{candidate.years_experience ?? 0} años</dd></div><div><dt>Fecha de aplicación</dt><dd>{candidate.applied_at || candidate.created_at ? new Date(candidate.applied_at || candidate.created_at || "").toLocaleDateString("es-ES") : "No indicada"}</dd></div></dl>}</section>
      <aside className="panel workflow"><p className="eyebrow">WORKFLOW</p><h2>Actualizar proceso</h2><label>Estado<select value={candidate.status} onChange={(event) => update("status", event.target.value as Status)}>{statuses.map((value) => <option value={value} key={value}>{statusLabels[value]}</option>)}</select></label><label>Etapa<select value={candidate.stage} onChange={(event) => update("stage", event.target.value as Stage)}>{stages.map((value) => <option value={value} key={value}>{stageLabels[value]}</option>)}</select></label></aside>
    </div>
    <section className="panel notes"><div className="section-heading"><div><p className="eyebrow">SEGUIMIENTO INTERNO</p><h2>Notas del proceso</h2></div><span className="note-count">{notes.length} notas</span></div><form className="note-form" onSubmit={addNote}><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Añade contexto de una llamada o entrevista..." aria-label="Nueva nota" /><button className="button button-primary">Añadir nota</button></form>{notesLoading ? <div className="state">Cargando notas...</div> : notes.length === 0 ? <div className="state">Todavía no hay notas para esta candidatura.</div> : <div className="notes-list">{notes.map((item) => <article className="note" key={item.id}><div><p>{item.content}</p><small>{item.created_at ? new Date(item.created_at).toLocaleString("es-ES") : "Nota interna"}</small></div><button className="button button-danger" onClick={() => removeNote(item.id)}>Eliminar</button></article>)}</div>}</section>
  </main>;
}
